spring:
  application:
    name: controle-medicamento
  security:
    user:
      name: admin
      password: adminpass
      roles: ADMIN
  datasource:
    url: jdbc:${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 8081